### ISSUE TITLE
Function Example

### ISSUE THREAD

**Issue by yusufarist** [zazaperwira/msaeDB#1]
Hello, can you (@zazaperwira) help me use this package? Is there any documentation of its use? For example, code samples and results? Thank you 😀✨

**Comment by zazaperwira** [comment]
Dear @myarist , kindly check https://rdocumentation.org/packages/msaeDB/versions/0.2.1 for the documentation of every function in this package, it provides the example code for every function. You can copy and run it in your R. Hope this can help you.

**Comment by yusufarist** [comment]
> Dear @myarist, kindly check https://rdocumentation.org/packages/msaeDB/versions/0.2.1 for the documentation of every function in this package, it provides the example code for every function. You can copy and run it in your R. Hope this can help you.

Hoho got it

![image](https://user-images.githubusercontent.com/43068424/120122340-65ca9400-c1d2-11eb-961a-b00959f06efd.png)

I think you (@zazaperwira) can put that link in the Repository Details, over there 👆🏻

Thank you for your kindly help 👋🏻
